name: IESO Excel Report Generator

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly at minute 0
  workflow_dispatch:      # Allow manual runs from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas lxml openpyxl requests

      - name: Run power.py script
        run: python power.py

      - name: Commit new Excel file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/*.xlsx
          git commit -m "Update IESO report from GitHub Actions"
          git push
