name: IESO Excel Report Generator

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes (UTC)
  workflow_dispatch:         # Allow manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas lxml openpyxl requests

      - name: Run power.py
        run: python power.py

      - name: Commit and push Excel files
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A output/*.xlsx
          git commit -m "Update IESO report from GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
